=encoding UTF-8

=begin pdf

=ff

=end pdf

=head1 1. PREFACE

This handbook (and Zeppe-Lin itself) is inspired and based on the
L<CRUX Handbook|http://crux.nu/Main/Documentation>.  The original
version was written by Per Lidén L<mailto:per@fukt.bth.se> and
maintained by CRUX Team.  This implementation was reworked and adapted
for Zeppe-Lin by Alexandr Savca L<mailto:alexandr.savca89@gmail.com>.

=cut

# vim: sw=4 ts=4 sts=4 et cc=72 tw=70
