=begin pdf

=ff

=end pdf

=head1 2. INTRODUCTION

Welcome to the Zeppe-Lin Handbook! It's not an extensive guide on how
to use and configure common Linux software.  The purpose of the
handbook is to explain how to install, configure, and maintain
Zeppe-Lin systems, and to highlight the differences between common
Linux distributions and Zeppe-Lin.

=begin html

=over

=item *

The online version of this handbook is placed
L<here|http://zeppel.ink/handbook.7.html>.

=item *

The pdf version of this handbook can be downloaded
L<here|http://zeppel.ink/handbook.7.pdf>.

=back

=end html

=over

=item *

The online version of this handbook is placed at:
L<http://zeppel.ink/handbook.7.html>.

=item *

The pdf version of this handbook can be downloaded at:
L<http://zeppel.ink/handbook.7.pdf>.

=item *

The local copy of this handbook can be installed on Zeppe-Lin system
by the following command:

    # pkgman install handbook

=back

=cut

# vim: sw=4 ts=4 sts=4 et cc=72 tw=70
