=head1 INTRODUCTION

=begin html

<img alt="Zeppe-Lin" class="logo" src="https://github.com/zeppe-lin/artwork/blob/master/logo-small.png?raw=true">

=end html

This handbook (as a whole Zeppe-Lin) is inspired and based on the
L<CRUX Handbook|http://crux.nu/Main/Documentation>.

=begin html

It is also available on the Zeppe-Lin system as a
<a href="https://github.com/zeppe-lin/handbook">handbook(7)</a>
manual page.

=end html

=begin comment

=head2 What is Zeppe-Lin?

=end comment

Zeppe-Lin is a lightweight GNU/Linux distribution for the x86-64
architecture targeted at experienced users.  It is forked from CRUX
and the primary focus of this distribution is "keep it simple" too.

The KISS principle reflects in a simple tar.gz-based package system,
BSD-style init scripts, and a relatively small collection of trimmed
packages.

The secondary focus is the utilization of new GNU/Linux features and
recent tools and libraries.

=begin comment

=head2 Why use Zeppe-Lin?

In short, B<Zeppe-Lin> might suit you very well if you are:

=over

=item *

an experienced user who wants a clean and simple GNU/Linux
distribution as a foundation of your installation;

=item *

a person who prefers editing configuration files with an editor to
using GUI;

=item *

someone who does not hesitate to download and compile programs from
the source;

=item *

someone who wants a KISS GNU/Linux distribution as a foundation of
your own distro;

=back

=end comment

=cut
